services:
  mcp-inspector:
    build:
      context: .
      dockerfile: ./docker/Inspector.Dockerfile
    restart: always
    working_dir: /app
    ports:
      - "5000:5173"
    volumes:
      - ./mcp:/app
    entrypoint: "npx @modelcontextprotocol/inspector python server.py"
