[tool.poetry]
name = "ollama-agents"
version = "0.1.0"
description = ""
authors = ["Tyler Buell"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
ollama = "^0.4.4"
fake-useragent = "^2.0.2"
requests = "^2.32.3"
python-dotenv = "^1.0.1"
pydantic = "^2.10.3"
docstring-parser = "^0.16"
bs4 = "^0.0.2"
groq = "^0.13.0"
markitdown = "^0.0.1a3"
pyodbc = "^5.2.0"
aiohttp = "^3.11.11"
colorlog = "^6.9.0"
mcp = "^1.4.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
