[tool.poetry]
name = "reactive-agents"
version = "0.1.0"
description = "A custom reactive AI Agent framework for LLM-driven task execution"
authors = ["Tyler Buell"]
readme = "README.md"
packages = [
    { include = "agents" },
    { include = "model_providers" },
    { include = "tools" },
    { include = "prompts" },
    { include = "loggers" },
    { include = "config" },
    { include = "agent_mcp" },
]

[tool.poetry.dependencies]
python = "^3.10"
ollama = "^0.4.4"
requests = "^2.32.3"
python-dotenv = "^1.0.1"
pydantic = "^2.10.3"
docstring-parser = "^0.16"
groq = "^0.13.0"
markitdown = "^0.0.1a3"
colorlog = "^6.9.0"
mcp = "^1.4.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
