name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run tests
        run: |
          # Set environment variables to disable potentially problematic components
          export DISABLE_MCP_CLIENT_SYSTEM_EXIT=1
          export PYTEST_TIMEOUT=60
          # Run tests with a timeout and additional parameters to help with CI environment
          poetry run pytest -v --cov=./ --cov-report=xml --timeout=60 --no-header --tb=native
        timeout-minutes: 5
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
